### ISSUE TITLE
Miscellaneous

### ISSUE THREAD

**Issue by sustained** [Elfayer/vue-land-bot#17]
Some ideas:

- [x] [`!code` - syntax highlighting tips](https://github.com/Elfayer/vue-land-bot/issues/19)
- [x] [`!coc` - code of conduct info](https://github.com/Elfayer/vue-land-bot/issues/20)
- [x] [`!dry` - don't repeat yourself](https://github.com/Elfayer/vue-land-bot/pull/40) (about copy-pasting questions in multiple channels)
- [x] [`!howtoask` - how to ask a good question?](https://github.com/Elfayer/vue-land-bot/issues/18)
- [x] [`!sharingcode` - info on using CodeSandbox/JSFiddle/CodePen?](https://github.com/Elfayer/vue-land-bot/pull/50)

Please contribute any ideas you have.
